spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/instasettle}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Aman2@sharma}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Web3j settings
web3j.client-address=${WEB3J_CLIENT_ADDRESS:http://127.0.0.1:8545}
contracts.path=${CONTRACTS_PATH:./contract-addresses.json}
